version: '3.3'
services:
  app:
    container_name: server
    build:
      context: ./
      dockerfile: Dockerfile
    image: demo/server
    networks:
      - cu-network
    command:  uvicorn main:app --reload --host 0.0.0.0  --port 8000
    environment:
      - LOG_LEVEL=debug
      - PGHOST=postgresdb
    volumes:
      - .:/app
    ports:
      - 8000:8000
    links:
      - "db:postgresdb"


  db:
    container_name: db
    image: postgres:13-alpine3.14
    hostname: postgresdb
    networks:
      - cu-network
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      - POSTGRES_USER=demo_user
      - PGPASSWORD=password123
      - POSTGRES_DB=demo

volumes:
  postgres_data:

networks:
  cu-network:
      driver: bridge




